In [51]:
import numpy as np
from sklearn.datasets import make_classification

In [ ]:

X, y = make_classification(n_samples=10000, n_features=5, n_informative=5,
                           n_redundant=0, n_repeated=0, n_classes=3,
                           n_clusters_per_class=1,
                           weights=[0.33, 0.33, 0.33],
                           class_sep=2, random_state=0)

In [13]:
X.shape

(10000, 5)

In [14]:
y.shape

(10000,)

In [5]:

X, y = make_classification(n_samples=10000, n_features=5, n_informative=5,
                           n_redundant=0, n_repeated=0, n_classes=3,
                           n_clusters_per_class=1,
                           weights=[0.33, 0.33, 0.33],
                           class_sep=2, random_state=0)

In [15]:
y

array([0, 0, 2, ..., 2, 0, 1])

In [16]:
y = to_categorical(y)

In [17]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [20]:

y = np.vstack((y[:, 0], y[:, :2].sum(axis=1))).T

In [21]:
y

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 1.],
       [0., 1.]], dtype=float32)

In [22]:
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from keras.metrics import binary_accuracy
from keras.utils.np_utils import to_categorical

In [26]:
clf = Sequential()
clf.add(Dense(5, activation='relu', input_dim=5))
clf.add(Dense(2, activation='sigmoid'))
clf.compile(loss='binary_crossentropy', optimizer=SGD(), metrics=[binary_accuracy])
clf.fit(X, y, epochs=20, batch_size=100, verbose=0)

In [27]:
clf.predict(X)

313/313 [==============================] - 0s 701us/step


array([[0.7240376 , 0.70555586],
       [0.7332167 , 0.8031145 ],
       [0.02407289, 0.5064826 ],
       ...,
       [0.23605552, 0.22160685],
       [0.78933126, 0.99301404],
       [0.01770477, 0.9985733 ]], dtype=float32)

In [1]:
import pandas as pd

In [2]:
dat_label = pd.read_csv('dataset.csv',index_col=0).T
#label = label.iloc[:12,:]
dat_smiles = pd.read_csv('smiles.csv', index_col=0)
s = dat_smiles.to_dict()
dict_smile = s['SMILES']

In [110]:
dat_label.iloc[:,57]

CID100031      0
CID10012081    0
CID10015       0
CID100197      0
CID10024       0
              ..
CID99870       0
CID9989        0
CID9989226     1
CID999         0
CID9990075     0
Name: odorless, Length: 5596, dtype: int64

In [4]:
from rdkit import Chem
from mordred import Calculator, descriptors

# create descriptor calculator with all descriptors
calc = Calculator(descriptors, ignore_3D=True)

len(calc.descriptors)

1613

In [5]:
mols = [Chem.MolFromSmiles(smi) for smi in dict_smile.values()]

In [6]:
df = calc.pandas(mols)

  2%|▉                                       | 132/5596 [00:03<03:43, 24.40it/s]

/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


  7%|██▉                                     | 416/5596 [00:09<01:37, 52.89it/s]

/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


  8%|███▏                                    | 444/5596 [00:10<01:25, 60.03it/s]

/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


 12%|████▉                                   | 695/5596 [00:15<01:46, 46.12it/s]

/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


 13%|█████▍                                  | 755/5596 [00:17<01:40, 48.23it/s]

/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


 21%|████████▎                              | 1191/5596 [00:26<01:27, 50.23it/s]

/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


 24%|█████████▍                             | 1358/5596 [00:30<01:34, 44.99it/s]

/home/ubuntu/anaconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


100%|███████████████████████████████████████| 5596/5596 [01:54<00:00, 48.70it/s]


In [9]:
df.to_csv('mordred.csv')

In [21]:
X = df.select_dtypes(include=[int, float]).to_numpy()

In [20]:
y = dat_label.to_numpy()

In [26]:
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from keras.metrics import binary_accuracy
from keras.utils.np_utils import to_categorical

2022-11-14 04:11:33.764970: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-14 04:11:33.916260: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-14 04:11:33.946749: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-14 04:11:34.451576: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; 

In [28]:
X.shape

(5596, 697)

In [43]:
clf = Sequential()
clf.add(Dense(256, activation='relu', input_dim=697))
#clf.add(Dense(64))
clf.add(Dense(91, activation='sigmoid'))
clf.compile(loss='binary_crossentropy', optimizer=SGD(), metrics=[binary_accuracy])
clf.fit(X, y, epochs=200, batch_size=100, verbose=0)

In [58]:
def pred(output):
    pred  = np.where(output> 0.5, 1, output)
    pred  = np.where(pred< 0.5, 0, pred)
    return pred


In [53]:
output = clf.predict(X)

175/175 [==============================] - 0s 838us/step


In [54]:
output 

array([[0.37753412, 0.37405664, 0.3766518 , ..., 0.37531406, 0.3930189 ,
        0.40520158],
       [0.37753412, 0.37405664, 0.3766518 , ..., 0.37531406, 0.3930189 ,
        0.40520158],
       [0.37753412, 0.37405664, 0.3766518 , ..., 0.37531406, 0.3930189 ,
        0.40520158],
       ...,
       [0.37753412, 0.37405664, 0.3766518 , ..., 0.37531406, 0.3930189 ,
        0.40520158],
       [0.37753412, 0.37405664, 0.3766518 , ..., 0.37531406, 0.3930189 ,
        0.40520158],
       [0.37753412, 0.37405664, 0.3766518 , ..., 0.37531406, 0.39301887,
        0.40520158]], dtype=float32)

In [60]:
preds = pred(output)

In [67]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report

In [65]:
roc_auc_score(y,preds)

0.5000761363347969

In [68]:
cl = classification_report(y,preds)

/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [103]:
report = pd.DataFrame(columns = ['label','precision','recall','ROC'],index = range(91))

In [107]:
for i in range(91):
    cl = classification_report(y.transpose()[i],preds.transpose()[i],output_dict=True)
    report.iloc[i,0] = i
    report.iloc[i,1] = cl['1']['precision']
    report.iloc[i,2] = cl['1']['recall']
    report.iloc[i,3] = roc_auc_score(y.transpose()[i],preds.transpose()[i])

/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.

/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.

/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.

/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.

/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.

/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/anaconda/lib/python3.

In [109]:
report.to_csv('MLPreport.csv')